simple queries 
SELECT BUSNO FROM BUS WHERE ROUTENAME LIKE '%BLR%' order by busno ASC;
SELECT DEPTNAME FROM GOVERNMENT WHERE OWNERNO>1200 ORDER BY deptname ASC;
aggregate functions
SELECT COUNT(*) AS COUNT_AGENT FROM AGENT HAVING COUNT(*)>3;
SELECT COUNT(BUSNO) FROM OWNER WHERE OWNERNO IN(SELECT OWNERNO FROM GOVERNMENT WHERE DEPTNAME='HRRTC') GROUP BY busno;
set operations
SELECT PNAME AS NAME FROM PASSENGER INTERSECT(SELECT ANAME AS NAME FROM AGENT) ORDER BY NAME DESC;
SELECT PNAME AS NAME FROM PASSENGER UNION(SELECT OWNERNAME AS NAME FROM OWNER) ORDER BY NAME DESC;
nested query 
SELECT * FROM OWNER WHERE BUSNO IN (SELECT BUS.BUSNO FROM BUS,PASSENGER WHERE BUS.BUSNO=PASSENGER.BUSNO);

